server:
  servlet:
    context-path: /api

spring:
  profiles:
    active:
      - dev
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

queue:
  name: rabbit-example
  exchange: exchange-example
  routingkey: routing-key-example
---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: queue
    port: 5673
    username: guest
    password: guest